# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'admin_dashboard.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(924, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Booklist = QtWidgets.QTableWidget(self.centralwidget)
        self.Booklist.setGeometry(QtCore.QRect(60, 80, 741, 441))
        self.Booklist.setMinimumSize(QtCore.QSize(721, 441))
        self.Booklist.setMaximumSize(QtCore.QSize(16777215, 441))
        self.Booklist.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.Booklist.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContentsOnFirstShow)
        self.Booklist.setRowCount(15)
        self.Booklist.setObjectName("Booklist")
        self.Booklist.setColumnCount(4)
        item = QtWidgets.QTableWidgetItem()
        self.Booklist.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.Booklist.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.Booklist.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.Booklist.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.Booklist.setItem(0, 0, item)
        self.Booklist.horizontalHeader().setVisible(True)
        self.Booklist.horizontalHeader().setCascadingSectionResizes(True)
        self.Booklist.horizontalHeader().setDefaultSectionSize(180)
        self.Booklist.horizontalHeader().setStretchLastSection(False)
        self.Booklist.verticalHeader().setCascadingSectionResizes(False)
        self.Booklist.verticalHeader().setDefaultSectionSize(30)
        self.Booklist.verticalHeader().setHighlightSections(False)
        self.SearchBar = QtWidgets.QLineEdit(self.centralwidget)
        self.SearchBar.setGeometry(QtCore.QRect(300, 20, 461, 41))
        self.SearchBar.setCursorPosition(6)
        self.SearchBar.setClearButtonEnabled(True)
        self.SearchBar.setObjectName("SearchBar")
        self.Savebtn = QtWidgets.QPushButton(self.centralwidget)
        self.Savebtn.setGeometry(QtCore.QRect(130, 20, 113, 32))
        self.Savebtn.setObjectName("Savebtn")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 924, 37))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        item = self.Booklist.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Title"))
        item = self.Booklist.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Year"))
        item = self.Booklist.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Author"))
        item = self.Booklist.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Available "))
        __sortingEnabled = self.Booklist.isSortingEnabled()
        self.Booklist.setSortingEnabled(False)
        self.Booklist.setSortingEnabled(__sortingEnabled)
        self.SearchBar.setText(_translate("MainWindow", "Search"))
        self.Savebtn.setText(_translate("MainWindow", "Save"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
