# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Login.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1849, 792)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("background-color: rgb(237, 229, 218);")
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(650, 50, 650, 50)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMaximumSize(QtCore.QSize(16777215, 1000))
        self.frame.setStyleSheet("background-color: rgba(41, 38, 35, 0.75);\n"
"border-radius: 20px; /* creates rounded corners */\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_4.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout_4.setContentsMargins(50, 10, 50, 10)
        self.gridLayout_4.setVerticalSpacing(0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_4.setSpacing(20)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.usernameLbl = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.usernameLbl.sizePolicy().hasHeightForWidth())
        self.usernameLbl.setSizePolicy(sizePolicy)
        self.usernameLbl.setMinimumSize(QtCore.QSize(0, 44))
        self.usernameLbl.setMaximumSize(QtCore.QSize(16777215, 44))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.usernameLbl.setFont(font)
        self.usernameLbl.setStyleSheet("color: white;\n"
"background: transparent;\n"
"padding-left: 10px;")
        self.usernameLbl.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.usernameLbl.setObjectName("usernameLbl")
        self.horizontalLayout_4.addWidget(self.usernameLbl)
        self.label = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(0, 44))
        self.label.setMaximumSize(QtCore.QSize(16777215, 44))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setStyleSheet("color: white;\n"
"background: transparent;\n"
"padding-left: 10px;")
        self.label.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label.setObjectName("label")
        self.horizontalLayout_4.addWidget(self.label)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout.setSpacing(20)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.usernameInput = QtWidgets.QLineEdit(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.usernameInput.sizePolicy().hasHeightForWidth())
        self.usernameInput.setSizePolicy(sizePolicy)
        self.usernameInput.setMaximumSize(QtCore.QSize(16777215, 80))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.usernameInput.setFont(font)
        self.usernameInput.setStyleSheet("QLineEdit {\n"
"color: white;\n"
"background: transparent;\n"
"border-radius: 10px; /* creates rounded corners */\n"
"border: 1px solid black;\n"
"padding-left: 5px;\n"
"background-color: rgba(41, 38, 35, 0.9);\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 1px solid white;  /* border when selected */\n"
"}")
        self.usernameInput.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.usernameInput.setObjectName("usernameInput")
        self.horizontalLayout.addWidget(self.usernameInput)
        self.passwordInput = QtWidgets.QLineEdit(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.passwordInput.sizePolicy().hasHeightForWidth())
        self.passwordInput.setSizePolicy(sizePolicy)
        self.passwordInput.setMaximumSize(QtCore.QSize(16777215, 80))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.passwordInput.setFont(font)
        self.passwordInput.setStyleSheet("QLineEdit {\n"
"color: white;\n"
"background: transparent;\n"
"border-radius: 10px; /* creates rounded corners */\n"
"border: 1px solid black;\n"
"padding-left: 5px;\n"
"background-color: rgba(41, 38, 35, 0.9);\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 1px solid white;  /* border when selected */\n"
"}")
        self.passwordInput.setEchoMode(QtWidgets.QLineEdit.Password)
        self.passwordInput.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.passwordInput.setObjectName("passwordInput")
        self.horizontalLayout.addWidget(self.passwordInput)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.gridLayout_12 = QtWidgets.QGridLayout()
        self.gridLayout_12.setContentsMargins(-1, 222, -1, -1)
        self.gridLayout_12.setHorizontalSpacing(20)
        self.gridLayout_12.setVerticalSpacing(30)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(-1, 20, -1, -1)
        self.horizontalLayout_2.setSpacing(20)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.btnLoginstudent = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnLoginstudent.sizePolicy().hasHeightForWidth())
        self.btnLoginstudent.setSizePolicy(sizePolicy)
        self.btnLoginstudent.setMaximumSize(QtCore.QSize(16777215, 60))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btnLoginstudent.setFont(font)
        self.btnLoginstudent.setStyleSheet("QPushButton {\n"
"color: white;\n"
"background: transparent;\n"
"border-radius: 10px; /* creates rounded corners */\n"
"border: 1px solid black;\n"
"padding-left: 5px;\n"
"background-color: rgba(41, 38, 35, 0.9);\n"
"}\n"
"QPushButton:hover {\n"
"    border: 1px solid white;  /* border when selected */\n"
"}")
        self.btnLoginstudent.setObjectName("btnLoginstudent")
        self.horizontalLayout_2.addWidget(self.btnLoginstudent)
        self.btnLoginadmin = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnLoginadmin.sizePolicy().hasHeightForWidth())
        self.btnLoginadmin.setSizePolicy(sizePolicy)
        self.btnLoginadmin.setMaximumSize(QtCore.QSize(16777215, 60))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btnLoginadmin.setFont(font)
        self.btnLoginadmin.setStyleSheet("QPushButton {\n"
"color: white;\n"
"background: transparent;\n"
"border-radius: 10px; /* creates rounded corners */\n"
"border: 1px solid black;\n"
"padding-left: 5px;\n"
"background-color: rgba(41, 38, 35, 0.9);\n"
"}\n"
"QPushButton:hover {\n"
"    border: 1px solid white;  /* border when selected */\n"
"}")
        self.btnLoginadmin.setObjectName("btnLoginadmin")
        self.horizontalLayout_2.addWidget(self.btnLoginadmin)
        spacerItem1 = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.gridLayout_12.addLayout(self.horizontalLayout_2, 1, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(20)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem2 = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.btnRegister = QtWidgets.QPushButton(self.frame)
        self.btnRegister.setMaximumSize(QtCore.QSize(16777215, 60))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btnRegister.setFont(font)
        self.btnRegister.setStyleSheet("QPushButton {\n"
"color: white;\n"
"background: transparent;\n"
"border-radius: 10px; /* creates rounded corners */\n"
"border: 1px solid black;\n"
"padding-left: 5px;\n"
"background-color: rgba(41, 38, 35, 0.9);\n"
"}\n"
"QPushButton:hover {\n"
"    border: 1px solid white;  /* border when selected */\n"
"}")
        self.btnRegister.setObjectName("btnRegister")
        self.horizontalLayout_3.addWidget(self.btnRegister)
        self.btnClear = QtWidgets.QPushButton(self.frame)
        self.btnClear.setMaximumSize(QtCore.QSize(16777215, 60))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btnClear.setFont(font)
        self.btnClear.setStyleSheet("QPushButton {\n"
"color: white;\n"
"background: transparent;\n"
"border-radius: 10px; /* creates rounded corners */\n"
"border: 1px solid black;\n"
"padding-left: 5px;\n"
"background-color: rgba(41, 38, 35, 0.9);\n"
"}\n"
"QPushButton:hover {\n"
"    border: 1px solid white;  /* border when selected */\n"
"}")
        self.btnClear.setObjectName("btnClear")
        self.horizontalLayout_3.addWidget(self.btnClear)
        spacerItem3 = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.gridLayout_12.addLayout(self.horizontalLayout_3, 2, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_12)
        self.verticalLayout.setStretch(2, 1)
        self.gridLayout_4.addLayout(self.verticalLayout, 1, 0, 1, 1)
        self.lblCreateAccount = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblCreateAccount.sizePolicy().hasHeightForWidth())
        self.lblCreateAccount.setSizePolicy(sizePolicy)
        self.lblCreateAccount.setMinimumSize(QtCore.QSize(0, 55))
        self.lblCreateAccount.setMaximumSize(QtCore.QSize(16777215, 80))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.lblCreateAccount.setFont(font)
        self.lblCreateAccount.setStyleSheet("color: white;\n"
"background: transparent;\n"
"")
        self.lblCreateAccount.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.lblCreateAccount.setObjectName("lblCreateAccount")
        self.gridLayout_4.addWidget(self.lblCreateAccount, 0, 0, 1, 1)
        self.lblStatus = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblStatus.sizePolicy().hasHeightForWidth())
        self.lblStatus.setSizePolicy(sizePolicy)
        self.lblStatus.setMinimumSize(QtCore.QSize(253, 0))
        self.lblStatus.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setFamily("Inter Variable Text")
        font.setPointSize(11)
        self.lblStatus.setFont(font)
        self.lblStatus.setStyleSheet("color: white;\n"
"background: transparent;\n"
"")
        self.lblStatus.setText("")
        self.lblStatus.setAlignment(QtCore.Qt.AlignCenter)
        self.lblStatus.setObjectName("lblStatus")
        self.gridLayout_4.addWidget(self.lblStatus, 4, 0, 1, 1)
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.usernameLbl.setText(_translate("MainWindow", "Username"))
        self.label.setText(_translate("MainWindow", "Password"))
        self.btnLoginstudent.setText(_translate("MainWindow", "Login Student"))
        self.btnLoginadmin.setText(_translate("MainWindow", "Login Admin"))
        self.btnRegister.setText(_translate("MainWindow", "Register New User"))
        self.btnClear.setText(_translate("MainWindow", "Clear Form"))
        self.lblCreateAccount.setText(_translate("MainWindow", "Login"))
