# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'studentDashboard2.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1389, 1001)
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 4, 6, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem1, 5, 5, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(80, 40, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 2, 1, 1, 1)
        self.dashboardLbl = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dashboardLbl.sizePolicy().hasHeightForWidth())
        self.dashboardLbl.setSizePolicy(sizePolicy)
        self.dashboardLbl.setMaximumSize(QtCore.QSize(16777215, 150))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.dashboardLbl.setFont(font)
        self.dashboardLbl.setStyleSheet("background-color: white;\n"
"color: rgb(110, 99, 93);")
        self.dashboardLbl.setObjectName("dashboardLbl")
        self.gridLayout.addWidget(self.dashboardLbl, 0, 2, 1, 5)
        spacerItem3 = QtWidgets.QSpacerItem(80, 40, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 4, 4, 1, 1)
        self.widget_2 = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_2.sizePolicy().hasHeightForWidth())
        self.widget_2.setSizePolicy(sizePolicy)
        self.widget_2.setMinimumSize(QtCore.QSize(0, 250))
        self.widget_2.setMaximumSize(QtCore.QSize(16777215, 16777211))
        self.widget_2.setStyleSheet("background-color: white; border-radius: 10px; background-color: rgb(237, 229, 218);")
        self.widget_2.setObjectName("widget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget_2)
        self.gridLayout_2.setContentsMargins(20, 20, 20, 20)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.libraryHoursLbl = QtWidgets.QLabel(self.widget_2)
        font = QtGui.QFont()
        font.setFamily("Inter Variable Text SemiBold")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.libraryHoursLbl.setFont(font)
        self.libraryHoursLbl.setStyleSheet("color: rgb(17, 24, 39);")
        self.libraryHoursLbl.setObjectName("libraryHoursLbl")
        self.gridLayout_2.addWidget(self.libraryHoursLbl, 0, 0, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSpacing(5)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.weekdayHoursLbl = QtWidgets.QLabel(self.widget_2)
        font = QtGui.QFont()
        font.setFamily("Inter Variable Text")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.weekdayHoursLbl.setFont(font)
        self.weekdayHoursLbl.setStyleSheet("color: rgb(17, 24, 39);")
        self.weekdayHoursLbl.setObjectName("weekdayHoursLbl")
        self.verticalLayout_2.addWidget(self.weekdayHoursLbl)
        self.weekendHoursLbl = QtWidgets.QLabel(self.widget_2)
        font = QtGui.QFont()
        font.setFamily("Inter Variable Text")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.weekendHoursLbl.setFont(font)
        self.weekendHoursLbl.setStyleSheet("color: rgb(17, 24, 39);")
        self.weekendHoursLbl.setObjectName("weekendHoursLbl")
        self.verticalLayout_2.addWidget(self.weekendHoursLbl)
        self.gridLayout_2.addLayout(self.verticalLayout_2, 1, 1, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.weekdayLbl = QtWidgets.QLabel(self.widget_2)
        font = QtGui.QFont()
        font.setFamily("Inter Variable Text")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.weekdayLbl.setFont(font)
        self.weekdayLbl.setStyleSheet("color: rgb(75, 85, 99);")
        self.weekdayLbl.setObjectName("weekdayLbl")
        self.verticalLayout.addWidget(self.weekdayLbl)
        self.weekendLbl = QtWidgets.QLabel(self.widget_2)
        font = QtGui.QFont()
        font.setFamily("Inter Variable Text")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.weekendLbl.setFont(font)
        self.weekendLbl.setStyleSheet("color: rgb(75, 85, 99);")
        self.weekendLbl.setObjectName("weekendLbl")
        self.verticalLayout.addWidget(self.weekendLbl)
        self.gridLayout_2.addLayout(self.verticalLayout, 1, 0, 1, 1)
        self.gridLayout.addWidget(self.widget_2, 4, 5, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMinimumSize(QtCore.QSize(0, 720))
        self.groupBox.setStyleSheet("background-color: rgb(237, 229, 218);")
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_5.setContentsMargins(-1, 20, -1, 20)
        self.verticalLayout_5.setSpacing(20)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setContentsMargins(-1, 100, -1, 50)
        self.verticalLayout_3.setSpacing(30)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.dashboardBtn = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dashboardBtn.sizePolicy().hasHeightForWidth())
        self.dashboardBtn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Inter Variable Text Medium")
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.dashboardBtn.setFont(font)
        self.dashboardBtn.setStyleSheet("QPushButton {\n"
"    border-radius: 10px;\n"
"    background-color: white; \n"
"    text-align: left; \n"
"    padding-left: 30px;\n"
"    color: rgb(74, 66, 62);\n"
"\n"
"}\n"
"QPushButton:hover {\n"
"    border: 2px solid rgb(110, 99, 93);;\n"
"    background-color: rgb(212, 244, 211);\n"
"}")
        self.dashboardBtn.setObjectName("dashboardBtn")
        self.verticalLayout_3.addWidget(self.dashboardBtn)
        self.myBooksBtn = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.myBooksBtn.sizePolicy().hasHeightForWidth())
        self.myBooksBtn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Inter Variable Text Medium")
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.myBooksBtn.setFont(font)
        self.myBooksBtn.setStyleSheet("QPushButton {\n"
"    border-radius: 10px;\n"
"    background-color: white; \n"
"    text-align: left; \n"
"    padding-left: 30px;\n"
"    color: rgb(74, 66, 62);\n"
"\n"
"}\n"
"QPushButton:hover {\n"
"    border: 2px solid rgb(110, 99, 93);;\n"
"    background-color: rgb(212, 244, 211);\n"
"}")
        self.myBooksBtn.setObjectName("myBooksBtn")
        self.verticalLayout_3.addWidget(self.myBooksBtn)
        self.browseLibraryBtn = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.browseLibraryBtn.sizePolicy().hasHeightForWidth())
        self.browseLibraryBtn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Inter Variable Text Medium")
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.browseLibraryBtn.setFont(font)
        self.browseLibraryBtn.setStyleSheet("QPushButton {\n"
"    border-radius: 10px;\n"
"    background-color: white; \n"
"    text-align: left; \n"
"    padding-left: 30px;\n"
"    color: rgb(74, 66, 62);\n"
"\n"
"}\n"
"QPushButton:hover {\n"
"    border: 2px solid rgb(110, 99, 93);;\n"
"    background-color: rgb(212, 244, 211);\n"
"}")
        self.browseLibraryBtn.setObjectName("browseLibraryBtn")
        self.verticalLayout_3.addWidget(self.browseLibraryBtn)
        self.ReservationsBtn = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ReservationsBtn.sizePolicy().hasHeightForWidth())
        self.ReservationsBtn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Inter Variable Text Medium")
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.ReservationsBtn.setFont(font)
        self.ReservationsBtn.setStyleSheet("QPushButton {\n"
"    border-radius: 10px;\n"
"    background-color: white; \n"
"    text-align: left; \n"
"    padding-left: 30px;\n"
"    color: rgb(74, 66, 62);\n"
"\n"
"}\n"
"QPushButton:hover {\n"
"    border: 2px solid rgb(110, 99, 93);;\n"
"    background-color: rgb(212, 244, 211);\n"
"}")
        self.ReservationsBtn.setObjectName("ReservationsBtn")
        self.verticalLayout_3.addWidget(self.ReservationsBtn)
        self.historyBtn = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.historyBtn.sizePolicy().hasHeightForWidth())
        self.historyBtn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Inter Variable Text Medium")
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.historyBtn.setFont(font)
        self.historyBtn.setStyleSheet("QPushButton {\n"
"    border-radius: 10px;\n"
"    background-color: white; \n"
"    text-align: left; \n"
"    padding-left: 30px;\n"
"    color: rgb(74, 66, 62);\n"
"\n"
"}\n"
"QPushButton:hover {\n"
"    border: 2px solid rgb(110, 99, 93);;\n"
"    background-color: rgb(212, 244, 211);\n"
"}")
        self.historyBtn.setObjectName("historyBtn")
        self.verticalLayout_3.addWidget(self.historyBtn)
        self.favoritesBtn = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.favoritesBtn.sizePolicy().hasHeightForWidth())
        self.favoritesBtn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Inter Variable Text Medium")
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.favoritesBtn.setFont(font)
        self.favoritesBtn.setStyleSheet("QPushButton {\n"
"    border-radius: 10px;\n"
"    background-color: white; \n"
"    text-align: left; \n"
"    padding-left: 30px;\n"
"    color: rgb(74, 66, 62);\n"
"\n"
"}\n"
"QPushButton:hover {\n"
"    border: 2px solid rgb(110, 99, 93);;\n"
"    background-color: rgb(212, 244, 211);\n"
"}")
        self.favoritesBtn.setObjectName("favoritesBtn")
        self.verticalLayout_3.addWidget(self.favoritesBtn)
        self.verticalLayout_5.addLayout(self.verticalLayout_3)
        self.line = QtWidgets.QFrame(self.groupBox)
        self.line.setStyleSheet("color: rgb(17, 24, 39);")
        self.line.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line.setLineWidth(1)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setObjectName("line")
        self.verticalLayout_5.addWidget(self.line)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setContentsMargins(-1, 50, -1, 150)
        self.verticalLayout_4.setSpacing(30)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.settingsBtn = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.settingsBtn.sizePolicy().hasHeightForWidth())
        self.settingsBtn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Inter Variable Text Medium")
        font.setPointSize(13)
        self.settingsBtn.setFont(font)
        self.settingsBtn.setStyleSheet("QPushButton {\n"
"    border-radius: 10px;\n"
"    background-color: white; \n"
"    text-align: left; \n"
"    padding-left: 30px;\n"
"    color: rgb(74, 66, 62);\n"
"\n"
"}\n"
"QPushButton:hover {\n"
"    border: 2px solid rgb(110, 99, 93);;\n"
"    background-color: rgb(212, 244, 211);\n"
"}")
        self.settingsBtn.setObjectName("settingsBtn")
        self.verticalLayout_4.addWidget(self.settingsBtn)
        self.helpBtn = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.helpBtn.sizePolicy().hasHeightForWidth())
        self.helpBtn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Inter Variable Text Medium")
        font.setPointSize(13)
        self.helpBtn.setFont(font)
        self.helpBtn.setStyleSheet("QPushButton {\n"
"    border-radius: 10px;\n"
"    background-color: white; \n"
"    text-align: left; \n"
"    padding-left: 30px;\n"
"    color: rgb(74, 66, 62);\n"
"\n"
"}\n"
"QPushButton:hover {\n"
"    border: 2px solid rgb(110, 99, 93);;\n"
"    background-color: rgb(212, 244, 211);\n"
"}")
        self.helpBtn.setObjectName("helpBtn")
        self.verticalLayout_4.addWidget(self.helpBtn)
        self.verticalLayout_5.addLayout(self.verticalLayout_4)
        self.verticalLayout_5.setStretch(0, 4)
        self.verticalLayout_5.setStretch(2, 2)
        self.gridLayout.addWidget(self.groupBox, 0, 0, 6, 1)
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setStyleSheet("background-color: white;")
        self.widget.setObjectName("widget")
        self.widget_3 = QtWidgets.QWidget(self.widget)
        self.widget_3.setGeometry(QtCore.QRect(20, 340, 40, 640))
        self.widget_3.setStyleSheet("background-color: white;")
        self.widget_3.setObjectName("widget_3")
        self.gridLayout.addWidget(self.widget, 0, 1, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 80, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem4, 1, 3, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem5, 3, 5, 1, 1)
        self.booksTableWidget = QtWidgets.QTableWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.booksTableWidget.sizePolicy().hasHeightForWidth())
        self.booksTableWidget.setSizePolicy(sizePolicy)
        self.booksTableWidget.setStyleSheet("QTableWidget {\n"
"    border: 2px solid rgb(110, 99, 93);\n"
"}\n"
"\n"
"\n"
"QHeaderView::section:horizontal {\n"
"    background-color: #c3b0a5;\n"
"    color: black;\n"
"    text-align: left;\n"
"    padding-left: 15px;\n"
"    padding-top: 15px;\n"
"    padding-bottom: 15px;\n"
"}\n"
"\n"
"")
        self.booksTableWidget.setShowGrid(True)
        self.booksTableWidget.setGridStyle(QtCore.Qt.SolidLine)
        self.booksTableWidget.setObjectName("booksTableWidget")
        self.booksTableWidget.setColumnCount(3)
        self.booksTableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(11)
        item.setFont(font)
        item.setBackground(QtGui.QColor(195, 176, 165))
        self.booksTableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(11)
        item.setFont(font)
        item.setBackground(QtGui.QColor(195, 176, 165))
        self.booksTableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(11)
        item.setFont(font)
        item.setBackground(QtGui.QColor(195, 176, 165))
        self.booksTableWidget.setHorizontalHeaderItem(2, item)
        self.gridLayout.addWidget(self.booksTableWidget, 2, 3, 1, 1)
        self.gridLayout.setColumnStretch(0, 1)
        self.gridLayout.setColumnStretch(3, 4)
        self.gridLayout.setRowStretch(0, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.dashboardLbl.setText(_translate("MainWindow", "Dashboard"))
        self.libraryHoursLbl.setText(_translate("MainWindow", "Library Hours"))
        self.weekdayHoursLbl.setText(_translate("MainWindow", "8AM - 8PM"))
        self.weekendHoursLbl.setText(_translate("MainWindow", "9AM - 8PM"))
        self.weekdayLbl.setText(_translate("MainWindow", "Monday - Friday"))
        self.weekendLbl.setText(_translate("MainWindow", "Saturday - Sunday"))
        self.dashboardBtn.setText(_translate("MainWindow", "Dashboard"))
        self.myBooksBtn.setText(_translate("MainWindow", "My Books"))
        self.browseLibraryBtn.setText(_translate("MainWindow", "Browse Library"))
        self.ReservationsBtn.setText(_translate("MainWindow", "Reservations"))
        self.historyBtn.setText(_translate("MainWindow", "History"))
        self.favoritesBtn.setText(_translate("MainWindow", "Favorites"))
        self.settingsBtn.setText(_translate("MainWindow", "Settings"))
        self.helpBtn.setText(_translate("MainWindow", "Help"))
        item = self.booksTableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Title"))
        item = self.booksTableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Author"))
        item = self.booksTableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Due Date"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
